language: php
php:
    - 5.5

#env:
#  - DB=sqlite

before_script:
  - mysql -e 'create database symfony;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create -n
  - php app/console doctrine:schema:create -n
  - php app/console doctrine:fixtures:load -n

script:
  - phpunit -c app

notifications:
  email:
    -  marcmorales83@gmail.com

branches:
  only:
    - master
    - devel