imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ Demofony2AppBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
           node: %node%
           node_paths: [%node_paths%]
           apply_to:   "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#fosUser bundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Demofony2\UserBundle\Entity\User

#vich uploader
vich_uploader:
    db_driver: orm
    mappings:
        category_image:
            uri_prefix: /uploads/images/category
            upload_destination: %kernel.root_dir%/../web/uploads/images/category
            inject_on_load: true
            delete_on_remove: true
            delete_on_update: true
            namer: vich_uploader.namer_origname

# JMS i18n Routing
jms_i18n_routing:
    default_locale: "%locale%"
    locales: [ ca, es, en ]
    strategy: prefix

# JMS Translations
jms_translation:
    configs:
        app:
            dirs: [ %kernel.root_dir%, %kernel.root_dir%/../src ]
            output_dir: %kernel.root_dir%/Resources/translations
            excluded_names: [ "*TestCase.php", "*Test.php" ]
            excluded_dirs: [ cache, data, logs, Application ]
            extractors: [jms_i18n_routing]

# Doctrine Extensions Bundle
stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
            translatable:   false
            softdeleteable: true
            timestampable:  true
            sluggable:      false

# Sonata Block Bundle
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

#sonata admin
sonata_admin:
    title: 'Demofony2'
    title_logo: /bundles/espaideltapage/images/logo.png
#    templates:
#        # default global templates
#        layout:  :Admin:layout.html.twig
#        ajax:    SonataAdminBundle::ajax_layout.html.twig
#
#        # default value if done set, actions templates, should extend global templates
#        list:    SonataAdminBundle:CRUD:list.html.twig
#        show:    SonataAdminBundle:CRUD:show.html.twig
#        edit:    SonataAdminBundle:CRUD:edit.html.twig
#        user_block:   :Admin:user_block.html.twig