fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    options: { i18n: false }

JMSTranslationBundle_ui:
    resource: @JMSTranslationBundle/Controller/
    type:     annotation
    prefix:   /admin/trans

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    options: { i18n: false }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    options: { i18n: false }

demofony2_app:
    resource: "@Demofony2AppBundle/Resources/config/routing.yml"
    prefix:   /

