security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_EDITOR]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:      ^/*
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    true
                use_referer:        true
                check_path:     /login_check
                failure_path:   null
                default_target_path: /
                always_use_default_target_path: false
            logout:
                path:           /logout
                target:         /
            anonymous:    true
            remember_me:
                key:  "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /.*
                domain: ~
            switch_user: { role: ROLE_ADMIN }
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~

    access_control:
        # Public dev tools
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Public login routes
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Private routes
        - { path: ^/admin, role: [ROLE_ADMIN] }
        # Rest of all domain
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
