services:
    app.user.event_listener:
        class: Demofony2\UserBundle\Event\UserListener
        arguments: [@translator, @session, @router]
        tags:
              - { name: kernel.event_subscriber }
