services:
    demofony2_user.registration.form.type:
        class: Demofony2\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: demofony2_user_registration }
