services:
    sonata.admin.category:
        class: Demofony2\AppBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Process Participation', label: 'Category'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\Category
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.proposal_answer:
        class: Demofony2\AppBundle\Admin\ProposalAnswerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Process Participation', label: 'Proposal Answer'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\ProposalAnswer
            - Demofony2AppBundle:Admin\Admin

    sonata.admin.process_participation:
        class: Demofony2\AppBundle\Admin\ProcessParticipationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Process Participation', label: 'Process Participation'}
        arguments:
            - null
            - Demofony2\AppBundle\Entity\ProcessParticipation
            - Demofony2AppBundle:Admin\Admin
