services:
    app.user_subscriber:
        class: Demofony2\AppBundle\Listener\UserSubscriber
        arguments: [@app.user_callable]
        tags:
              - { name: doctrine.event_subscriber, connection: default }
    app.comment_subscriber:
        class: Demofony2\AppBundle\Listener\CommentSubscriber
        tags:
              - { name: doctrine.event_subscriber, connection: default }