demofony2_app_front:
    resource: "@Demofony2AppBundle/Controller/Front"
    type:     annotation

demofony2_app_admin:
    resource: "@Demofony2AppBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin
