_demofony2_api_rest:
    type:     rest
    resource: Demofony2\AppBundle\Controller\Api\ProcessParticipationController
    options: { i18n: false }

demofony2_app_front:
    resource: "@Demofony2AppBundle/Controller/Front"
    type:     annotation

