services:
    app.user_callable:
        class: Demofony2\AppBundle\Security\UserCallable
        arguments: [@security.token_storage]

    app.authentication_handler:
        class: Demofony2\AppBundle\AuthenticationHandler\AuthenticationHandler
        arguments:  [@router]