services:
    app.abstract_manager:
        abstract:  true
        arguments: [ @doctrine.orm.entity_manager, @validator ]

    app.process_participation:
        class: Demofony2\AppBundle\Manager\ProcessParticipationManager
        parent: app.abstract_manager
        arguments: [ @form.factory, @app.vote_permission_checker ]

    app.proposal:
        class: Demofony2\AppBundle\Manager\ProposalManager
        parent: app.abstract_manager
        arguments: [ @form.factory, @app.vote_permission_checker ]

    app.vote_permission_checker:
        class: Demofony2\AppBundle\Manager\VotePermissionCheckerService
        arguments: [ @doctrine.orm.entity_manager, @validator ]

# KNP menus
    app.menu.frontmenu:
        class: Demofony2\AppBundle\Menu\FrontendMenu
        arguments: [ "@knp_menu.factory", "@translator.default" ]
    app.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: app.menu.frontmenu
        factory_method: createMainMenu
        arguments: [ "@request" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: frontend }
