services:
    app.abstract_manager:
        abstract:  true
        arguments: [@doctrine.orm.entity_manager, @validator]

    app.process_participation:
        class: Demofony2\AppBundle\Manager\ProcessParticipationManager
        parent: app.abstract_manager
