services:
    app.abstract_manager:
        abstract:  true
        arguments: [@doctrine.orm.entity_manager, @validator]

    app.process_participation:
        class: Demofony2\AppBundle\Manager\ProcessParticipationManager
        parent: app.abstract_manager
        arguments: [@form.factory, @app.vote_permission_checker]

    app.proposal:
        class: Demofony2\AppBundle\Manager\ProposalManager
        parent: app.abstract_manager
        arguments: [@form.factory]

    app.vote_permission_checker:
        class: Demofony2\AppBundle\Manager\VotePermissionCheckerManager
        arguments: [@doctrine.orm.entity_manager, @validator, @security.context]
